# Generated by Django 4.0.6 on 2022-08-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_listitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='todo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items_set', to='api.todoitem'),
        ),
    ]
