# Generated by Django 4.0.6 on 2022-08-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_listitem_todo_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='value',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='text_value',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='url_value',
            field=models.URLField(blank=True),
        ),
    ]
