# Generated by Django 4.0.6 on 2022-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_todoitem_value_todoitem_text_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='type',
            field=models.CharField(blank=True, choices=[('T', 'String'), ('L', 'List'), ('U', 'URL')], max_length=1, null=True),
        ),
    ]
