# Generated by Django 4.0.6 on 2022-08-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_todoitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='type',
            field=models.CharField(choices=[('T', 'String'), ('L', 'List'), ('U', 'URL')], default='T', max_length=1),
        ),
    ]
