# Generated by Django 4.0.6 on 2022-08-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_todoitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='todo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todoitem'),
        ),
    ]
