# Generated by Django 4.0.6 on 2022-08-06 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_listitem_todo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='todo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todoitem'),
        ),
    ]
