# Generated by Django 4.0.6 on 2022-08-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_listitem_todo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='todo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='api.todoitem'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='type',
            field=models.CharField(choices=[('T', 'String'), ('L', 'List'), ('U', 'URL')], max_length=1),
        ),
    ]
